#!/bin/bash
# potmaker - Updates .pot & .po files with any strings found in .php code
# version: 0.4 (Transifex support)
# (c) Júlio Reis 2014, licenced under GPL v3, see <http://www.gnu.org/licenses/>
# This code lives at https://github.com/Tintazul/potmaker

# find first .pot file; we will change this one
FILES="`find * -type f -iname '*.pot'`"
NFILES=`echo "$FILES" | wc -l`
if [ "$NFILES" -gt 1 ]; then
  echo "+++ WARNING: more than one .pot file found, updating the first one:"
  echo '+++' $FILES
fi

# generate .pot file
NEWTEMP="./new.pot"
echo "$NEWTEMP"
echo "Finding new strings..."
find . -type f -iname "*.php" | xgettext --from-code=UTF-8 --add-comments=Translators --keyword=__ --keyword=_e --keyword=_x --keyword=_ex --keyword=_n:1,2 -f - --sort-by-file -o $NEWTEMP

if [ -z "$NEWTEMP" ]; then
  echo "+++ INFO: No strings found, nothing changed"
  exit
fi

if [ -z "$FILES" ]; then
  # no previous .pot file found
  # saving the temp file in the current directory, with its basename
  PWD=`pwd`
  NEWFILE="./`basename $PWD`.pot"
  mv $NEWTEMP $NEWFILE
  echo "+++ INFO: No previous file found: $NEWFILE generated"
  echo "+++ INFO: Rename and place in appropriate directory as needed"
  exit
fi
TEMPLATE=`echo "$FILES" | head -1`
DIR=`dirname "$TEMPLATE"`

msgmerge -N -U $TEMPLATE $NEWTEMP

# If we’re using Transifex, we push the translation
if [ -f .tx/config ]; then
	tx push -s
else
	if [ ! -f $DIR/*.po ]; then
		echo "+++ INFO: No .po files found in directory '$DIR'"
	else
		# Merging to .po files
		for POFILE in $DIR/*.po
		do
	  		echo "Merging changes to $POFILE..."
			msgmerge -N -U $POFILE $TEMPLATE
		done
	fi
fi

echo "Cleaning up..."
rm -f $NEWTEMP $DIR/*~
